# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from miniature import miniature_pb2 as miniature_dot_miniature__pb2


class MiniatureStub(object):
    """The miniature service definition.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.RequestChunk = channel.unary_unary(
                '/Miniature/RequestChunk',
                request_serializer=miniature_dot_miniature__pb2.ChunkRequest.SerializeToString,
                response_deserializer=miniature_dot_miniature__pb2.ChunkReply.FromString,
                )


class MiniatureServicer(object):
    """The miniature service definition.
    """

    def RequestChunk(self, request, context):
        """Request a chunk
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MiniatureServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'RequestChunk': grpc.unary_unary_rpc_method_handler(
                    servicer.RequestChunk,
                    request_deserializer=miniature_dot_miniature__pb2.ChunkRequest.FromString,
                    response_serializer=miniature_dot_miniature__pb2.ChunkReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'Miniature', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Miniature(object):
    """The miniature service definition.
    """

    @staticmethod
    def RequestChunk(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Miniature/RequestChunk',
            miniature_dot_miniature__pb2.ChunkRequest.SerializeToString,
            miniature_dot_miniature__pb2.ChunkReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
